version: "3.9"
services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "--password=${MYSQL_ROOT_PASSWORD}",
        ]
      timeout: 20s
      retries: 10
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  front:
    build:
      context: .
      dockerfile: ./docker/front.dockerfile
    ports:
      - "4200:4200"

  api:
    image: node
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
    env_file:
      - .env
    ports:
      - "3333:3333"
