version: "3.9"
services:
  mysql:
    image: mysql:5.7
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "--password=${MYSQL_ROOT_PASSWORD}",
        ]
      timeout: 20s
      retries: 10
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_TCP_PORT= ${MYSQL_PORT}

  front:
    build:
      context: .
      dockerfile: ./docker/front.dockerfile
    ports:
      - "4200:4200"

  api:
    command: "yarn run start api --host 0.0.0.0"
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
    volumes:
      - ./apps/api:/app/apps/api
    env_file:
      - .env
    ports:
      - "3333:3333"
