version: "3.9"
services:
  mysql:
    image: mysql:5.7
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "--password=${MYSQL_ROOT_PASSWORD}",
        ]
      timeout: 20s
      retries: 10
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_TCP_PORT= ${MYSQL_PORT}

  front:
    build:
      context: .
      dockerfile: ./docker/front.dockerfile
    volumes:
    - ./apps/contact-list:/app/apps/contact-list
    ports:
      - "4200:4200"

  api:
    command: sh -c "yarn run migration:up-docker && yarn run start api --host 0.0.0.0"
    depends_on:
      mysql:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
    volumes:
      - ./apps/api:/app/apps/api
      - ./dist:/app/dist/
    env_file:
      - .env
    ports:
      - "3333:3333"
